### ISSUE TITLE
Title component puts <p> inside <span>

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/coding-blog-plugin#10]
My home page contains this HTML (which I made more readable by modifying the whitespace).
```HTML
<span style="text-shadow: none; font-size: 48px">
  <span style="font-size: 24px;  margin-bottom: -48px; display: block">Blog of&nbsp;</span>
  <p>Tyson Williams</p>
</span>
```

The W3C validator doesn't like that `p` is inside `span`.  [This SO answer](https://stackoverflow.com/questions/18492256/displaying-an-element-similar-to-p-inside-a-span/18492639#18492639) suggests changing the outer `span` to `div`.  Of the several tweaks that I tried, this was the only one that didn't alter the appearance (in latest Google Chrome for Windows).

If this is the correct fix, then I can create a PR that makes this change.

**Comment by bender2k14** [comment]
Yes, that line, but...

Oh, great thought.  You were right to be concerned.  W3C doesn't like `<div>`s inside `<h1>` either.

**Comment by loreanvictor** [comment]
I think it does need to be an `h1` so that any third-party tool will correctly understand its role in the document (the main title) (tools such as search engine crawlers, RSS readers, etc.). So I suspect the best compromise right now is to not be 100% W3C compliant as long as browsers render the content properly.

**Comment by bender2k14** [comment]
It does look fine to me on the browser-OS pairs that I have seen.  I was just thinking that I could fix a W3C validator error.  Oh well.
