### ISSUE TITLE
Author component using `src=github` doesn't show the correct author

### ISSUE THREAD

**Issue by JoshuaWalsh** [CONNECT-platform/coding-blog-plugin#18]
I've just launched my blog [here](https://joshwalsh.coding.blog/). For some reason the Author component for my index page says "Eugene Ghanizadeh Khoub" (probably because that's who last last edited the boilerplate) and my blog posts all say "Anonymous Author" (probably because the posts don't exist in the boilerplate project).

What do I need to do in order to have these update to my name? I'd rather not have to manually enter all my details on each post, in case some of my details change in future.

My repo is [here](https://github.com/JoshuaWalsh/joshwalsh.coding.blog) if you want to see what I've done.

**Comment by bender2k14** [comment]
You should change [your GitHub config](https://github.com/JoshuaWalsh/joshwalsh.coding.blog/blob/09aaf4b1d8ee1fbd4940fccf4faa7d781f8cd4b2/.codedoc/config.ts#L36-L39) to
```
github: {
  repo: 'joshwalsh.coding.blog',         // --> change this to change your github repo
  user: 'JoshuaWalsh'         // --> change this to change your github username
}
```

In the [GitHub documentation for `coding-blog-plugin`](https://connect-platform.github.io/coding-blog-plugin/author#automatic-inference), this information is given under the heading "Important" because it is...uhh...important ;)

**Comment by bender2k14** [comment]
That should fix the author reference for your index page that says "Eugene Ghanizadeh Khoub".

I am less sure about why your posts say "Anonymous Author".

**Comment by loreanvictor** [comment]
> my index page says "Eugene Ghanizadeh Khoub" (probably because that's who last last edited the boilerplate) and my blog posts all say "Anonymous Author" (probably because the posts don't exist in the boilerplate project).

Yes, that is because (as @bender2k14 mentioned) the reference repository to check against is set to the boilerplate repository not yours. The posts that exist then get me as the last author in that repo and posts that do not exist in the boilerplate repo will be "Anonymous" (which is the default).

@JoshuaWalsh since you are the second person who have encountered this, I will give higher priority to [this CLI feature](https://github.com/CONNECT-platform/codedoc-cli/issues/1) to avoid similar confusion in the future. I will keep this issue open until the referenced issue is resolved.

**Comment by loreanvictor** [comment]
So I added a `check` command (i.e. `codedoc check`) that will check your configuration for you and warn you of these kind of mistakes to the CLI. Not deployed yet, and have to add it to the documentation as well. Will be deployed via `@codedoc/cli@0.2.3`. Closing this issue for now.

**Comment by JoshuaWalsh** [comment]
Can I suggest that you add this to the README of the [boilerplate project](https://github.com/CONNECT-platform/coding-blog-boilerplate)? It wasn't obvious to me to look at the documentation of `coding-blog-plugin`, because the process of setting up a blog using the boilerplate means you don't ever really interact with `coding-blog-plugin`. (I had heard of it, but only because I was trying to find the source code for the Hero component and found it via a Google search)

**Comment by bender2k14** [comment]
Seems reasonable to me.

What do you think of PR https://github.com/CONNECT-platform/coding-blog-boilerplate/pull/11?

**Comment by loreanvictor** [comment]
@bender2k14 perfect, merged it. I also added some further instructions to the boilerplate project's README. Also I will add some [more config checks](https://github.com/CONNECT-platform/codedoc-cli/issues/3) to `codedoc check` and will add it to all documentation as well. Generally I suppose `codedoc check` should become the main way to instruct people how to configure **CODEDOC** projects properly.
