### ISSUE TITLE
Footnotes feature

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/coding-blog-plugin#19]
If a footnotes feature somewhat like Wikipedia or LaTeX existed, then I would use it.

If it were implemented with XML, then it might look something like...

```
This is paragraph one.<footnote>This is a footnote one.</footnote>

This is paragraph two.<footnote>This is a footnote two.</footnote>

<footnotes/>
```

...and get rendered like...

```
    This is paragraph one.1

    This is paragraph two.2

    1 This is footnote one.
    2 This is footnote two.
```

...where the numbers `1` and `2` are superscripts and hyperlinked in both directions.

Is this difficult to implement?

**Comment by loreanvictor** [comment]
Nope. There is only one consideration for this: I suspect footnotes must be _inline_ (i.e. in the middle of other text), which limits the markdown you can put inside them (for example no lists or no links, since **CODEDOC**'s inline components are a customized syntax of links already). This means that you would need to be able to set _internal_ identifiers for footnotes, and sometimes just reference them internally while writing the footnote content separately inside a quoted component.

With that consideration in mind, I suspect it would look something like this:

```md
This is paragraph one [This is footnote one](:Footnote).

This is paragraph two [](:Footnote (id=something))

> :Footnote id=something
>
> This is footnote two (and [here](https://google.com) is also a link).

> :Footnotes
```

As for implementation, I would recommend the components acting as mere markers and having a post-processor that then would go through each document and organize and render the footnotes.

**Comment by loreanvictor** [comment]
this feels like having a much broader use case than just for blogs (specifically I suspect lots of use-case for general software documentation), which means perhaps being supported directly by [**CODEDOC**](https://github.com/CONNECT-platform/codedoc) would be more appropriate. I have created [the corresponding ticket on **CODEDOC**](https://github.com/CONNECT-platform/codedoc/issues/67), so I am going to close this one.
