### ISSUE TITLE
Automate publishing of coding-blog-plugin

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog-plugin#20]
This is a spin off of https://github.com/CONNECT-platform/codedoc/issues/68#issuecomment-683850233.

I would like to automate the steps used to publish `coding-blog-plugin` to NPM.

@loreanvictor, can you tell me the specific steps you take and commands you execute to publish `coding-blog-plugin` to NPM?  The steps might include
1. installing build tools,
2. restoring dependencies,
3. building,
4. testing,
5. creating the package, and
6. publishing the package.

**Comment by loreanvictor** [comment]
@bender2k14 so right now the process is as follows:

There is an [_internal_ export](../blob/master/src/internal.ts) of plugin functionality that allows using the plugin code within its documentation (with some considerations, since the plugin and the documentation have two separate sets of dependencies). This is [used on the docs](https://github.com/CONNECT-platform/coding-blog-plugin/blob/3c8d2890cc4d7a342e30d00c59c35d387bcef67b/.codedoc/config.ts#L6) to verify and document new functionality.

So for each new functionality (a component, post-processor, etc):
- It is first coded, the code is tested via the docs. This means testing the feature and documenting it almost happen simultaneously
- Then I typically do a commit titled "bump version" ([example](https://github.com/CONNECT-platform/coding-blog-plugin/commit/63eff5b72b7e81ee14bfcec4bac418bdc8c04e0c)), in which merely the version of the package is increased.
- Then I run `npm publish`.

To be honest features of the package haven't had many surface consistency issues or similar things to raise the alarm for automated testing (unlike the CLI, for example). It is mostly seeing if something "looks good" since they _mostly_ don't have much complex functionality (this might not be the case in the future). Still, _some_ automated testing ensuring some basic functionality perhaps wouldn't hurt. Besides that, I guess the main thing that can be automated is publishing when there is a _bump version_ commit, so I am unsure how much could this particular library benefit from automated publishing process (since it is already pretty simplistic).
